// <auto-generated />
using System;
using ClickCart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickCart.Migrations
{
    [DbContext(typeof(ClickCartDbContext))]
    [Migration("20250220170522_UpdateODvsCI")]
    partial class UpdateODvsCI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClickCart.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("ClickCart.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ClickCart.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"), 1L, 1);

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ClickCart.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Đồ ăn vặt",
                            Description = "Đồ ăn vặt"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Gia vị",
                            Description = "Gia vị"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Nước giải khát",
                            Description = "Nước giải khát"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Thực phẩm ăn liền",
                            Description = "Thực phẩm ăn liền"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Thực phẩm tươi sống",
                            Description = "Thực phẩm tươi sống"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Dụng cụ nhà bếp",
                            Description = "Dụng cụ nhà bếp"
                        });
                });

            modelBuilder.Entity("ClickCart.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CreatedAt = new DateTime(2025, 2, 16, 0, 5, 22, 3, DateTimeKind.Local).AddTicks(1906),
                            FullName = "Nguyễn Việt Tùng",
                            PaymentGateway = "Credit Card",
                            PaymentStatus = "Paid",
                            PhoneNumber = "0123456789",
                            ShippingAddress = "123 Main Street, Hanoi",
                            TotalAmount = 60000,
                            UserID = 7
                        },
                        new
                        {
                            OrderID = 2,
                            CreatedAt = new DateTime(2025, 2, 18, 0, 5, 22, 3, DateTimeKind.Local).AddTicks(1918),
                            FullName = "Nguyễn Văn Toàn",
                            PaymentGateway = "COD",
                            PaymentStatus = "Pending",
                            PhoneNumber = "0123456789",
                            ShippingAddress = "456 Secondary Street, HCM",
                            TotalAmount = 65000,
                            UserID = 8
                        },
                        new
                        {
                            OrderID = 3,
                            CreatedAt = new DateTime(2025, 2, 20, 0, 5, 22, 3, DateTimeKind.Local).AddTicks(1920),
                            FullName = "Phạm Xuân Cường",
                            PaymentGateway = "Bank Transfer",
                            PaymentStatus = "Paid",
                            PhoneNumber = "0123456789",
                            ShippingAddress = "789 Tertiary Avenue, Da Nang",
                            TotalAmount = 250000,
                            UserID = 9
                        });
                });

            modelBuilder.Entity("ClickCart.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"), 1L, 1);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            OrderID = 1,
                            Price = 20000,
                            ProductID = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailID = 2,
                            OrderID = 1,
                            Price = 10000,
                            ProductID = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailID = 3,
                            OrderID = 2,
                            Price = 15000,
                            ProductID = 3,
                            Quantity = 3
                        },
                        new
                        {
                            OrderDetailID = 4,
                            OrderID = 2,
                            Price = 12000,
                            ProductID = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailID = 5,
                            OrderID = 3,
                            Price = 120000,
                            ProductID = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailID = 6,
                            OrderID = 3,
                            Price = 120000,
                            ProductID = 6,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ClickCart.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "Snack khoai tây giòn rụm, vị phô mai thơm ngon.",
                            ImageUrl = "Do_An_Vat/Bánh gạo Jinju cốm sữa.png",
                            IsAlcoholic = false,
                            Price = 20000,
                            ProductName = "Bánh gạo Jinju cốm sữa",
                            Stock = 50
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "Bánh quế Oreo vị vani hộp 54g.",
                            ImageUrl = "Do_An_Vat/Bánh quế Oreo vị vani hộp 54g.png",
                            IsAlcoholic = false,
                            Price = 10000,
                            ProductName = "Bánh quế Oreo vị vani hộp 54g",
                            Stock = 100
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Description = "Bánh quy bơ Cosy thập cẩm rắc hạt hộp 336g.",
                            ImageUrl = "Do_An_Vat/Bánh quy bơ Cosy thập cẩm rắc hạt hộp 336g.png",
                            IsAlcoholic = false,
                            Price = 15000,
                            ProductName = "Bánh quy bơ Cosy thập cẩm rắc hạt hộp 336g",
                            Stock = 200
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Description = "Bánh quy bơ Danisa hộp 908g.",
                            ImageUrl = "Do_An_Vat/Bánh quy bơ Danisa hộp 908g.png",
                            IsAlcoholic = false,
                            Price = 12000,
                            ProductName = "Bánh quy bơ Danisa hộp 908g",
                            Stock = 150
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Description = "Hộp Bánh Pocky Glico 118g.",
                            ImageUrl = "Do_An_Vat/Hộp Bánh Pocky Glico 118g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Hộp Bánh Pocky Glico 118g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Description = "Hộp quà Tết Hamper 1 x 6H 727.2g",
                            ImageUrl = "Do_An_Vat/Hộp quà Tết Hamper 1 x 6H 727.2g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Hộp quà Tết Hamper 1 x 6H 727.2g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 1,
                            Description = "Kẹo sing gum hương bạc hà và khuynh diệp CooL Air Wrigley's hộp 58,4g.",
                            ImageUrl = "Do_An_Vat/Kẹo sing gum hương bạc hà và khuynh diệp CooL Air Wrigley's hộp 58,4g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Kẹo sing gum hương bạc hà và khuynh diệp CooL Air Wrigley's hộp 58,4g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 1,
                            Description = "Kẹo Socola Snickers Túi 3 thanh 51g",
                            ImageUrl = "Do_An_Vat/Kẹo Socola Snickers Túi 3 thanh 51g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Kẹo Socola Snickers Túi 3 thanh 51g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 1,
                            Description = "Kẹo Socola Sữa Popit Tết 90.1g.",
                            ImageUrl = "Do_An_Vat/Kẹo Socola Sữa Popit Tết 90.1g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Kẹo Socola Sữa Popit Tết 90.1g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 1,
                            Description = "Khoai tây LAY'S vị tự nhiên classic 150g.",
                            ImageUrl = "Do_An_Vat/Khoai tây LAY'S vị tự nhiên classic 150g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Khoai tây LAY'S vị tự nhiên classic 150g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 1,
                            Description = "Mít sấy Vinamit gói 100g.",
                            ImageUrl = "Do_An_Vat/Mít sấy Vinamit gói 100g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mít sấy Vinamit gói 100g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 1,
                            Description = "Snach khoai tây Lay's tôm hùm cay lon 105 g.",
                            ImageUrl = "Do_An_Vat/Snach khoai tây Lay's tôm hùm cay lon 105 g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snach khoai tây Lay's tôm hùm cay lon 105 g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 1,
                            Description = "Snack Lay Stax khoai tây vị tự nhiên 160g.",
                            ImageUrl = "Do_An_Vat/Snack Lay Stax khoai tây vị tự nhiên 160g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack Lay Stax khoai tây vị tự nhiên 160g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 2,
                            Description = "Bột canh i-ốt Hải Châu gói 190g.",
                            ImageUrl = "Gia_Vi/Bột canh i-ốt Hải Châu gói 190g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bột canh i-ốt Hải Châu gói 190g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 2,
                            Description = "Bột ngọt (mì chính) Ajinomoto 2kg.",
                            ImageUrl = "Gia_Vi/Bột ngọt (mì chính) Ajinomoto 2kg.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bột ngọt (mì chính) Ajinomoto 2kg",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 2,
                            Description = "Bột ngọt (mì chính) Ajinomoto 400g.",
                            ImageUrl = "Gia_Vi/Bột ngọt (mì chính) Ajinomoto 400g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bột ngọt (mì chính) Ajinomoto 400g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 2,
                            Description = "Dầu hào Lee Kum Kee Kum Chun chai 255g.",
                            ImageUrl = "Gia_Vi/Dầu hào Lee Kum Kee Kum Chun chai 255g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Dầu hào Lee Kum Kee Kum Chun chai 255g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 2,
                            Description = "Dầu hào Maggi chai 350g.",
                            ImageUrl = "Gia_Vi/Dầu hào Maggi chai 350g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Dầu hào Maggi chai 350g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 2,
                            Description = "Gia vị nêm sẵn lẩu Thái Aji-Quick gói 50g.",
                            ImageUrl = "Gia_Vi/Gia vị nêm sẵn lẩu Thái Aji-Quick gói 50g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Gia vị nêm sẵn lẩu Thái Aji-Quick gói 50g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 2,
                            Description = "Nước mắm Phú Quốc Thanh Quốc 35 độ đạm.",
                            ImageUrl = "Gia_Vi/Nước mắm Phú Quốc Thanh Quốc 35 độ đạm.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước mắm Phú Quốc Thanh Quốc 35 độ đạm",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 2,
                            Description = "Bột ngọt (mì chính) Miwon gói 454g.",
                            ImageUrl = "Gia_Vi/Bột ngọt (mì chính) Miwon gói 454g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bột ngọt (mì chính) Miwon gói 454g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 2,
                            Description = "Tương ớt chua ngọt Cholimex chai 270g.",
                            ImageUrl = "Gia_Vi/Tương ớt chua ngọt Cholimex chai 270g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Tương ớt chua ngọt Cholimex chai 270g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 2,
                            Description = "Tương ớt chua ngọt Cholimex PET 2.1kg.",
                            ImageUrl = "Gia_Vi/Tương ớt chua ngọt Cholimex PET 2.1kg.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Tương ớt chua ngọt Cholimex PET 2.1kg",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 3,
                            Description = "Cà phê hòa tan 3in1 G7 hộp 288g.",
                            ImageUrl = "Nuoc_Giai_Khat/Cà phê hòa tan 3in1 G7 hộp 288g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Cà phê hòa tan 3in1 G7 hộp 288g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 3,
                            Description = "Cà phê sữa đá Highlands Coffee lon 235ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Cà phê sữa đá Highlands Coffee lon 235ml.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Cà phê sữa đá Highlands Coffee lon 235ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 3,
                            Description = "Nước giải khát Coca Cola chai 1.5lít.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước giải khát Coca Cola chai 1.5lít.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước giải khát Coca Cola chai 1.5lít",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 3,
                            Description = "Nước khoáng thiên nhiên LaVie 1.5 lít.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước khoáng thiên nhiên LaVie 1.5 lít.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước khoáng thiên nhiên LaVie 1.5 lít",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 3,
                            Description = "Nước uống sữa trái cây bổ dưỡng hương cam Nutri Boost chai 1L.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước uống sữa trái cây bổ dưỡng hương cam Nutri Boost chai 1L.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước uống sữa trái cây bổ dưỡng hương cam Nutri Boost chai 1L",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 3,
                            Description = "Nước uống tăng lực Việt Redbull lon 250ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước uống tăng lực Việt Redbull lon 250ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước uống tăng lực Việt Redbull lon 250ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 3,
                            Description = "Nước uống tinh khiết Dasani chai 1.5 lít.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước uống tinh khiết Dasani chai 1.5 lít.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước uống tinh khiết Dasani chai 1.5 lít",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 31,
                            CategoryID = 3,
                            Description = "Thùng 24 lon bia Hà Nội Habeco 330ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Thùng 24 lon bia Hà Nội Habeco 330ml.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 24 lon bia Hà Nội Habeco 330ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 32,
                            CategoryID = 3,
                            Description = "Thùng 24 lon bia Heineken 330ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Thùng 24 lon bia Heineken 330ml.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 24 lon bia Heineken 330ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 33,
                            CategoryID = 3,
                            Description = "Thùng 24 lon Bia Saigon lager 330ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Thùng 24 lon Bia Saigon lager 330ml.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 24 lon Bia Saigon lager 330ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 34,
                            CategoryID = 3,
                            Description = "Thùng 36 hộp sữa đậu nành Fami canxi ít đường 200ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Thùng 36 hộp sữa đậu nành Fami canxi ít đường 200ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 36 hộp sữa đậu nành Fami canxi ít đường 200ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 35,
                            CategoryID = 3,
                            Description = "Trà bí đao Wonderfarm lon 310ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Trà bí đao Wonderfarm lon 310ml.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Trà bí đao Wonderfarm lon 310ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 36,
                            CategoryID = 4,
                            Description = "Cháo thịt bằm Vifon gói 70g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Cháo thịt bằm Vifon gói 70g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Cháo thịt bằm Vifon gói 70g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 37,
                            CategoryID = 4,
                            Description = "Mì gói ăn liền cay Shin Ramyun Nongshim 114g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì gói ăn liền cay Shin Ramyun Nongshim 114g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì gói ăn liền cay Shin Ramyun Nongshim 114g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 38,
                            CategoryID = 4,
                            Description = "Phở gà Đệ Nhất gói 65g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Phở gà Đệ Nhất gói 65g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Phở gà Đệ Nhất gói 65g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 39,
                            CategoryID = 4,
                            Description = "Thùng 24 ly mì Hảo Hảo vị tôm chua cay Acecook 67g - Ly.",
                            ImageUrl = "Thuc_Pham_An_Lien/Thùng 24 ly mì Hảo Hảo vị tôm chua cay Acecook 67g - Ly.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 24 ly mì Hảo Hảo vị tôm chua cay Acecook 67g - Ly",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 40,
                            CategoryID = 4,
                            Description = "Thùng 24 ly mì Hảo Hảo vị tôm chua cay Acecook 67g - Ly.",
                            ImageUrl = "Thuc_Pham_An_Lien/Thùng 24 ly mì Hảo Hảo vị tôm chua cay Acecook 67g - Ly.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 24 ly mì Hảo Hảo vị tôm chua cay Acecook 67g - Ly",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 41,
                            CategoryID = 4,
                            Description = "Thùng 30 gói mì tôm chua cay Hảo Hảo Vina Acecook 75g - Thùng.",
                            ImageUrl = "Thuc_Pham_An_Lien/Thùng 30 gói mì tôm chua cay Hảo Hảo Vina Acecook 75g - Thùng.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thùng 30 gói mì tôm chua cay Hảo Hảo Vina Acecook 75g - Thùng",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 42,
                            CategoryID = 1,
                            Description = "Bánh snack Poca mực lăn muối ớt.",
                            ImageUrl = "Do_An_Vat/Bánh snack Poca mực lăn muối ớt.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bánh snack Poca mực lăn muối ớt",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 43,
                            CategoryID = 1,
                            Description = "Bắp Rang Bơ Thơm-Ngon-Giòn ONENUTS.",
                            ImageUrl = "Do_An_Vat/Bắp Rang Bơ Thơm-Ngon-Giòn ONENUTS.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bắp Rang Bơ Thơm-Ngon-Giòn ONENUTS",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 44,
                            CategoryID = 1,
                            Description = "Bim Bim Snack Bắp 4x Vị Cay Oishi.",
                            ImageUrl = "Do_An_Vat/Bim Bim Snack Bắp 4x Vị Cay Oishi.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bim Bim Snack Bắp 4x Vị Cay Oishi",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 45,
                            CategoryID = 1,
                            Description = "Kẹo Dẻo Hương Trái Cây Chupa Chups 1m.",
                            ImageUrl = "Do_An_Vat/Kẹo Dẻo Hương Trái Cây Chupa Chups 1m.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Kẹo Dẻo Hương Trái Cây Chupa Chups 1m",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 46,
                            CategoryID = 1,
                            Description = "Snack Cà Chua Tomati.",
                            ImageUrl = "Do_An_Vat/Snack Cà Chua Tomati.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack Cà Chua Tomati",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 47,
                            CategoryID = 1,
                            Description = "Snack hành Oishi Onion Rings.",
                            ImageUrl = "Do_An_Vat/Snack hành Oishi Onion Rings.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack hành Oishi Onion Rings",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 48,
                            CategoryID = 1,
                            Description = "SNACK KHOAI TÂY LAY’S VỊ TẢO BIỂN 95G.",
                            ImageUrl = "Do_An_Vat/SNACK KHOAI TÂY LAY’S VỊ TẢO BIỂN 95G.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "SNACK KHOAI TÂY LAY’S VỊ TẢO BIỂN 95G",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 49,
                            CategoryID = 1,
                            Description = "Snack khoai tây phô mai Karamucho Koikeya.",
                            ImageUrl = "Do_An_Vat/Snack khoai tây phô mai Karamucho Koikeya.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack khoai tây phô mai Karamucho Koikeya",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 50,
                            CategoryID = 1,
                            Description = "Snack Lay's Wavy vị thăn bò nướng texas 95g.",
                            ImageUrl = "Do_An_Vat/Snack Lay's Wavy vị thăn bò nướng texas 95g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack Lay's Wavy vị thăn bò nướng texas 95g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 51,
                            CategoryID = 1,
                            Description = "Snack Phô Mai Miếng Oishi.",
                            ImageUrl = "Do_An_Vat/Snack Phô Mai Miếng Oishi.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack Phô Mai Miếng Oishi",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 52,
                            CategoryID = 1,
                            Description = "Snack vị tôm cay Oishi.",
                            ImageUrl = "Do_An_Vat/Snack vị tôm cay Oishi.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Snack vị tôm cay Oishi",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 53,
                            CategoryID = 6,
                            Description = "Bộ thau rổ cao cấp Yoko.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Bộ thau rổ cao cấp Yoko.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bộ thau rổ cao cấp Yoko",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 54,
                            CategoryID = 6,
                            Description = "Đĩa sứ cao cấp.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Đĩa sứ cao cấp.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Đĩa sứ cao cấp",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 55,
                            CategoryID = 6,
                            Description = "Đũa tre dùng một lần Quang Hà.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Đũa tre dùng một lần Quang Hà.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Đũa tre dùng một lần Quang Hà",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 56,
                            CategoryID = 6,
                            Description = "Kéo nhà bếp KJ01 21cm.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Kéo nhà bếp KJ01 21cm.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Kéo nhà bếp KJ01 21cm",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 57,
                            CategoryID = 6,
                            Description = "Lô túi rác tiện dụng Soji.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Lô túi rác tiện dụng Soji.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Lô túi rác tiện dụng Soji",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 58,
                            CategoryID = 6,
                            Description = "Ly Thủy Tinh Luminarc.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Ly Thủy Tinh Luminarc.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Ly Thủy Tinh Luminarc",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 59,
                            CategoryID = 6,
                            Description = "Muôi múc canh Duxton.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Muôi múc canh Duxton.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Muôi múc canh Duxton",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 60,
                            CategoryID = 6,
                            Description = "Muỗng gỗ xào nấu.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Muỗng gỗ xào nấu.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Muỗng gỗ xào nấu",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 61,
                            CategoryID = 6,
                            Description = "Thìa inox Bếp Xinh.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Thìa inox Bếp Xinh.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thìa inox Bếp Xinh",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 62,
                            CategoryID = 6,
                            Description = "Thớt tre tự nhiên Sunhouse.",
                            ImageUrl = "Dung_Cu_Nha_Bep/Thớt tre tự nhiên Sunhouse.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Thớt tre tự nhiên Sunhouse",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 63,
                            CategoryID = 2,
                            Description = "Bột canh i-ốt Hải Châu.",
                            ImageUrl = "Gia_Vi/Bột canh i-ốt Hải Châu.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bột canh i-ốt Hải Châu",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 64,
                            CategoryID = 2,
                            Description = "Tương ớt chua ngọt Cholimex chai 270g.",
                            ImageUrl = "Gia_Vi/Tương ớt chua ngọt Cholimex chai 270g.png",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Tương ớt chua ngọt Cholimex chai 270g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 65,
                            CategoryID = 2,
                            Description = "Bột Ngọt Meizan.",
                            ImageUrl = "Gia_Vi/Bột Ngọt Meizan.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Bột Ngọt Meizan",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 66,
                            CategoryID = 2,
                            Description = "Cholimex Food - Tương ớt xí muội chai PET.",
                            ImageUrl = "Gia_Vi/Cholimex Food - Tương ớt xí muội chai PET.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Cholimex Food - Tương ớt xí muội chai PET",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 67,
                            CategoryID = 2,
                            Description = "Dầu đậu nành Simply chai 1 lít.",
                            ImageUrl = "Gia_Vi/Dầu đậu nành Simply chai 1 lít.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Dầu đậu nành Simply chai 1 lít",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 68,
                            CategoryID = 2,
                            Description = "Dầu hào chay Maggi nấm hương chai.",
                            ImageUrl = "Gia_Vi/Dầu hào chay Maggi nấm hương chai.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Dầu hào chay Maggi nấm hương chai",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 69,
                            CategoryID = 2,
                            Description = "Nước mắm Nam Ngư Cá Cơm Tươi.",
                            ImageUrl = "Gia_Vi/Nước mắm Nam Ngư Cá Cơm Tươi.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước mắm Nam Ngư Cá Cơm Tươi",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 70,
                            CategoryID = 2,
                            Description = "Sốt Mayonnaise Aji-Mayo Vị Chua Béo Chai 260g.",
                            ImageUrl = "Gia_Vi/Sốt Mayonnaise Aji-Mayo Vị Chua Béo Chai 260g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Sốt Mayonnaise Aji-Mayo Vị Chua Béo Chai 260g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 71,
                            CategoryID = 3,
                            Description = "7up lon 320ml vị chanh.",
                            ImageUrl = "Nuoc_Giai_Khat/7up lon 320ml vị chanh.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "7up lon 320ml vị chanh",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 72,
                            CategoryID = 2,
                            Description = "Chai nước tăng lực sting đỏ của pepsiCo 320ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Chai nước tăng lực sting đỏ của pepsiCo 320ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Chai nước tăng lực sting đỏ của pepsiCo 320ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 73,
                            CategoryID = 3,
                            Description = "Nước cam ép TH True Juice chai 350ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước cam ép TH True Juice chai 350ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước cam ép TH True Juice chai 350ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 74,
                            CategoryID = 3,
                            Description = "Nước ngọt Coca Cola lon 320ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước ngọt Coca Cola lon 320ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước ngọt Coca Cola lon 320ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 75,
                            CategoryID = 3,
                            Description = "Nước Sữa Trái Cây TH True Juice Milk Vị Cam Tự Nhiên Chai 300ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước Sữa Trái Cây TH True Juice Milk Vị Cam Tự Nhiên Chai 300ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước Sữa Trái Cây TH True Juice Milk Vị Cam Tự Nhiên Chai 300ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 76,
                            CategoryID = 3,
                            Description = "Nước tăng lực number1.",
                            ImageUrl = "Nuoc_Giai_Khat/Nước tăng lực number1.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Nước tăng lực number1",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 77,
                            CategoryID = 3,
                            Description = "Trà Đào TVT Chai 450Ml.",
                            ImageUrl = "Nuoc_Giai_Khat/Trà Đào TVT Chai 450Ml.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Trà Đào TVT Chai 450Ml",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 78,
                            CategoryID = 3,
                            Description = "Trà xanh hương chanh tuyết bạc hà C2 freeze.",
                            ImageUrl = "Nuoc_Giai_Khat/Trà xanh hương chanh tuyết bạc hà C2 freeze.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Trà xanh hương chanh tuyết bạc hà C2 freeze",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 79,
                            CategoryID = 3,
                            Description = "TRÀ XANH KHÔNG ĐỘ chai 455ML.",
                            ImageUrl = "Nuoc_Giai_Khat/TRÀ XANH KHÔNG ĐỘ chai 455ML.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "TRÀ XANH KHÔNG ĐỘ chai 455ML",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 80,
                            CategoryID = 4,
                            Description = "Mì 3 Miền Gold Tôm Chua Cay Đặc Biệt 75g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì 3 Miền Gold Tôm Chua Cay Đặc Biệt 75g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì 3 Miền Gold Tôm Chua Cay Đặc Biệt 75g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 81,
                            CategoryID = 4,
                            Description = "Mì Bò Hầm Ottogi 120G.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì Bò Hầm Ottogi 120G.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì Bò Hầm Ottogi 120G",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 82,
                            CategoryID = 4,
                            Description = "MÌ CUNG ĐÌNH VỊ LẨU TÔM CHUA CAY 80g.",
                            ImageUrl = "Thuc_Pham_An_Lien/MÌ CUNG ĐÌNH VỊ LẨU TÔM CHUA CAY 80g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "MÌ CUNG ĐÌNH VỊ LẨU TÔM CHUA CAY 80g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 83,
                            CategoryID = 4,
                            Description = "Mì Hảo Hảo big 100g tôm chua cay 100g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì Hảo Hảo big 100g tôm chua cay 100g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì Hảo Hảo big 100g tôm chua cay 100g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 84,
                            CategoryID = 4,
                            Description = "Mì khoai tây Omachi sườn hầm ngũ quả gói 80g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì khoai tây Omachi sườn hầm ngũ quả gói 80g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì khoai tây Omachi sườn hầm ngũ quả gói 80g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 85,
                            CategoryID = 4,
                            Description = "Mì khoai tây Omachi xốt bò hầm gói 80g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì khoai tây Omachi xốt bò hầm gói 80g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì khoai tây Omachi xốt bò hầm gói 80g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 86,
                            CategoryID = 4,
                            Description = "Mì Koreno vị kim chi gói 100g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì Koreno vị kim chi gói 100g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì Koreno vị kim chi gói 100g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 87,
                            CategoryID = 4,
                            Description = "Mì trộn Omachi xốt Spaghetti gói 90g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Mì trộn Omachi xốt Spaghetti gói 90g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Mì trộn Omachi xốt Spaghetti gói 90g",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 88,
                            CategoryID = 4,
                            Description = "MÌ TƯƠNG ĐEN BẮC KINH GÓI 83G.",
                            ImageUrl = "Thuc_Pham_An_Lien/MÌ TƯƠNG ĐEN BẮC KINH GÓI 83G.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "MÌ TƯƠNG ĐEN BẮC KINH GÓI 83G",
                            Stock = 30
                        },
                        new
                        {
                            ProductID = 89,
                            CategoryID = 4,
                            Description = "Phở trộn Đệ Nhất vị thập cẩm cay gói 82g.",
                            ImageUrl = "Thuc_Pham_An_Lien/Phở trộn Đệ Nhất vị thập cẩm cay gói 82g.jpg",
                            IsAlcoholic = false,
                            Price = 120000,
                            ProductName = "Phở trộn Đệ Nhất vị thập cẩm cay gói 82g",
                            Stock = 30
                        });
                });

            modelBuilder.Entity("ClickCart.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FreeShipCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("PremiumEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PremiumStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 20, 291, DateTimeKind.Local).AddTicks(2426),
                            Email = "HaiLTHE172555@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Lại Tuấn Hai",
                            PasswordHash = "$2a$11$9pjuVBdurkERC6RPnQ4YyOJd6cHG.nVDotwCKb2nZxDCc1DuDAIye",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Username = "HaiAdmin"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 20, 496, DateTimeKind.Local).AddTicks(7694),
                            Email = "HungPVHE161180@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Phạm Việt Hưng",
                            PasswordHash = "$2a$11$jt72renVbPFdbRg1rymE1el32rIkxfTZYcUTrLwIDABdznUk87f2.",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Username = "HungAdmin"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 20, 672, DateTimeKind.Local).AddTicks(373),
                            Email = "CongHTHE172673@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Hoàng Thành Công",
                            PasswordHash = "$2a$11$EhTyW5v3pPhHi.L7FUhyMOpUgXklZjXorIPUsimQCe8YUWHaUD7jW",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Username = "CongAdmin"
                        },
                        new
                        {
                            UserID = 4,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 20, 843, DateTimeKind.Local).AddTicks(6957),
                            Email = "NhatLVHE176909@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Lê Việt Nhật",
                            PasswordHash = "$2a$11$VHxSfE3PR/IXB5Jxvmd4bOd/V59PcweT.53doJutGjQ1h6gBdFVNi",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Username = "NhatAdmin"
                        },
                        new
                        {
                            UserID = 5,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 21, 44, DateTimeKind.Local).AddTicks(9239),
                            Email = "TrongLCPHS176090@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Lê Công Phú Trọng",
                            PasswordHash = "$2a$11$qgnlr67AsOIDXqkSW/sNSeA.L6M1KcETRzRTIIxD76C1wWDX8Fih.",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Username = "TrongAdmin"
                        },
                        new
                        {
                            UserID = 6,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 21, 211, DateTimeKind.Local).AddTicks(3264),
                            Email = "DatVTHS176109@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Vũ Tiến Đạt",
                            PasswordHash = "$2a$11$8MlnYeC.cbvs4r/NkUtykuq6Mep6Y6zN5FNTt3HGL6ZPQXT.W0Cvi",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Username = "DatAdmin"
                        },
                        new
                        {
                            UserID = 7,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 21, 409, DateTimeKind.Local).AddTicks(3172),
                            Email = "TungNVHE170677@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Nguyễn Việt Tùng",
                            PasswordHash = "$2a$11$vQOkm0uGSugJAm0aISSNie057.acI7wIOoH/mbIPKmtFQPhAkzOYK",
                            PhoneNumber = "0987654321",
                            Role = "Customer",
                            Username = "TungUser"
                        },
                        new
                        {
                            UserID = 8,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 21, 612, DateTimeKind.Local).AddTicks(921),
                            Email = "ToanPMHE171369@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Phan Mạnh Toàn",
                            PasswordHash = "$2a$11$nBQFLqiKv7KnkOOnIgKPu.ni2TMzunk/USD0kn3cMNfiAV4o2ufGu",
                            PhoneNumber = "0987654321",
                            Role = "Customer",
                            Username = "ToanUser"
                        },
                        new
                        {
                            UserID = 9,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 21, 823, DateTimeKind.Local).AddTicks(7047),
                            Email = "CuongPXHE172287@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Phạm Xuân Cường",
                            PasswordHash = "$2a$11$PGjojWiptAajTc.kiLSUy.e7KXf46.oHUZ0NcQDKPGjtoWysQUaue",
                            PhoneNumber = "0987654321",
                            Role = "Customer",
                            Username = "CuongUser"
                        },
                        new
                        {
                            UserID = 10,
                            CreatedAt = new DateTime(2025, 2, 21, 0, 5, 22, 3, DateTimeKind.Local).AddTicks(769),
                            Email = "AnhVNHE151076@fpt.edu.vn",
                            FreeShipCount = 0,
                            FullName = "Vũ Nam Anh",
                            PasswordHash = "$2a$11$oYQqw0ApelypcZXL6/zWRO14G5vJzH2mSYKLGi1B5gAffXGmokCZa",
                            PhoneNumber = "0123456789",
                            Role = "Customer",
                            Username = "AnhUser"
                        });
                });

            modelBuilder.Entity("ClickCart.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"), 1L, 1);

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VoucherID");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ClickCart.Models.Cart", b =>
                {
                    b.HasOne("ClickCart.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClickCart.Models.CartItem", b =>
                {
                    b.HasOne("ClickCart.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickCart.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClickCart.Models.Order", b =>
                {
                    b.HasOne("ClickCart.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClickCart.Models.OrderDetail", b =>
                {
                    b.HasOne("ClickCart.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickCart.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClickCart.Models.Product", b =>
                {
                    b.HasOne("ClickCart.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ClickCart.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ClickCart.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClickCart.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
